---

    - name: DEPLOY SNMP CONFIGURATIONS
      host: ios
      gather_facts: no
      connection: local

      tasks:
        
        - name: DEPLOY SNMP COMMANDS WITHIN COOKBOOK
          ios_config: 
            commands:
            username: "{{ un }}"
            password: "{{ pwd }}"
            host: "{{ inventory_hostname }}"

