---
- name: configure routers
  hosts: routers
  gather_facts: false
  connection: local
  tasks:
    - name: configure R1
      ios_config:
        lines:
          - host R1
    # - name: configure R1 interface e0/0
    #   ios_config:
    #     lines:
    #       - router-id 10.10.10.10
    #     parents: router ospf 100
    # - name: configure R1 interface e0/0
    #   ios_config:
    #     lines:
    #       - ip addr 192.168.1.10
    #     parents: interface Ethernet0/0
    - name: configure R2
      ios_config:
        lines:
          - host R2
    - name: configure R3
      ios_config:
        lines:
          - host R3

- name: configure switches
  hosts: switches
  gather_facts: false
  connection: local
  tasks:
    - name: configure SW1
      ios_config:
        lines:
          - host SW1
    - name: configure SW2
      ios_config:
        lines:
          - host Sw2
    - name: configure SW3
      ios_config:
        lines:
          - host SW3

- name: configure computers
  hosts: computers
  gather_facts: false
  connection: local
  tasks:
    - name: configure PC1
      ios_config:
        lines:
          - host PC1
    - name: configure PC2
      ios_config:
        lines:
          - host PC2
    - name: configure PC3
      ios_config:
        lines:
          - host PC3
    - name: configure PC4
      ios_config:
        lines:
          - host PC4
    - name: configure PC5
      ios_config:
        lines:
          - host PC5
    - name: configure PC6
      ios_config:
        lines:
          - host PC6
    - name: configure PC7
      ios_config:
        lines:
          - host PC7
    - name: configure PC8
      ios_config:
        lines:
          - host PC8
    - name: configure PC9
      ios_config:
        lines:
          - host PC9
    - name: configure PC10
      ios_config:
        lines:
          - host PC10
