---
- name: run show commands
  hosts: routers
  gather_facts: False
  tasks:
    - debug:
        msg: '{{ansible_host}} {{ansible_port}}'
    - name: Setup domain information
      shell: |
        set timeout 7
        # log_file {{ '~/logs/your_log_file.explog' }}

        spawn telnet {{ansible_host}} {{ansible_port}}

        expect "Escape character is '^]'."
        send "\n"

        expect "Router>"
        send "\nterm length 0"

        expect "Router>"
        send "\nen"

        expect "Router#"        
        send "\nconf t\nhost {{inventory_hostname}}\nend\nwr"      

      args:
        executable: /usr/bin/expect
      changed_when: yes
      delegate_to: localhost

      
      # telnet:
      #   port: '{{ansible_port}}'
      #   prompts:
      #     - "[>|#]"
      #   command:
      #     - term length 0
      #     - enable
      #     - show version
      #     - configure terminal
      #     - hostname PLEASE
      #     - end
      #     - write memory