---
- name: Configure Cisco IOU
  hosts: routers
  gather_facts: False
  tasks:
    - debug:
        msg: '{{ansible_host}} {{ansible_port}}'
    # - name: Get Past Prompts
    #   shell: |
    #     set timeout 90
    #     spawn telnet {{ansible_host}} {{ansible_port}}

    #     expect "Escape character is '^]'."
    #     send "\n"

    #     expect ""
    #     send "\n\n\n"
    #     sleep 30
    #     expect """
    #     send "no\n"
    #     expect ""
    #     send "\n\n\n"
    #     sleep 30
    #     expect ""
    #     send "\n"
    #   args:
    #     executable: /usr/bin/expect
    #   changed_when: yes
    #   delegate_to: localhost

    - name: Configure Devices
      shell: |
        set timeout 5
        
        spawn telnet {{ansible_host}} {{ansible_port}}

        expect "Escape character is '^]'."
        send "\n\n\n"

        # expect "% Please answer 'yes' or 'no'."
        # send "no\n\n"

        # sleep 5
        # expect "Press RETURN to get started!"
        # send "\n\n\n"
        # sleep 15
    
        expect "Router>"
        send "\n term length 0 \n en \n conf t \n host {{inventory_hostname}} \n end \n wr"
        
      args:
        executable: /usr/bin/expect
      changed_when: yes
      delegate_to: localhost

