---
- name: Configure Cisco IOU
  hosts: routers
  gather_facts: False
  tasks:
    - debug:
        msg: '{{ansible_host}} {{ansible_port}}'
    - name: Get past stupid prompts
      shell: |
        set timeout 60
        spawn telnet {{ansible_host}} {{ansible_port}}

        expect "Escape character is '^]'."
        send "\n"

        # send "\n\n\n"
        # sleep 60
        # send "no"
        # send "\n\n\n"
        # sleep 30
        # send "\n"

    - name: Configure Devices
      shell: |
        set timeout 5
        
        spawn telnet {{ansible_host}} {{ansible_port}}

        expect "Router>"
        send "\nterm length 0"

        expect "Router>"
        send "\nen"

        expect "Router#"        
        send "\nconf t\nhost {{inventory_hostname}}\nend\nwr"      

      args:
        executable: /usr/bin/expect
      changed_when: yes
      delegate_to: localhost



      # log_file {{ '~/logs/your_log_file.explog' }}
      # telnet:
      #   port: '{{ansible_port}}'
      #   prompts:
      #     - "[>|#]"
      #   command:
      #     - term length 0
      #     - enable
      #     - show version
      #     - configure terminal
      #     - hostname PLEASE
      #     - end
      #     - write memory