---
- name: Configure Routers through Telnet  
  hosts: routers
  gather_facts: no
  tasks:
    - name: Configure Router
      telnet:
        host: "{{ ansible_host }}"
        port: "{{ ansible_port }}"
        prompts:
        - "[>|#]"
        command:
        - term length 0
        - enable     
        - show version
        - conf t
        - hostname {{ inventory_hostname }}

