---
- name: Configure Routers through Telnet  
  hosts: routers
  gather_facts: False
  telnet:
    host: "{{ ansible_host }}"
    port: "{{ ansible_port }}"
    login_prompt: ">"
    user: "term length 0"
    prompts:
    - "[>|#]"
    command:
    - enable     
    - show version
    - configure terminal
    - hostname {{ inventory_hostname }}
    - end
    - write memory
